export const regionToTimezone = {
  "um-12": "Etc/GMT+12",
  um12: "Etc/GMT+12",

  as: "Pacific/Pago_Pago",
  nu: "Pacific/Niue",
  "um-11": "Pacific/Midway",

  ck: "Pacific/Rarotonga",
  "pf-10": "Pacific/Tahiti",
  "us-10n": "America/Adak",
  "us-10": "Pacific/Honolulu",
  "um-10": "Etc/GMT+10",
  "pf-930": "Pacific/Marquesas",

  "pf-9": "Pacific/Gambier",
  "us-9": "America/Anchorage",

  "mx-8": "America/Tijuana",
  "mx-8b": "America/Tijuana",
  "ca-8": "America/Vancouver",
  "us-8": "America/Los_Angeles",
  "us-8n": "America/Los_Angeles",
  pn: "Pacific/Pitcairn",

  "ca-7n": "America/Whitehorse",
  "ca-7": "America/Edmonton",
  "mx-7": "America/Mazatlan",
  "mx-7b": "America/Hermosillo",
  "us-7": "America/Denver",
  "us-7n": "America/Phoenix",

  bz: "America/Belize",
  "ca-6n": "America/Regina",
  "ca-6": "America/Winnipeg",
  cr: "America/Costa_Rica",
  "ec-6": "Pacific/Galapagos",
  sv: "America/El_Salvador",
  gt: "America/Guatemala",
  hn: "America/Tegucigalpa",
  "mx-6": "America/Mexico_City",
  "mx-6b": "America/Mexico_City",
  ni: "America/Managua",
  "us-6": "America/Chicago",

  "br-5": "America/Rio_Branco",
  "ca-5n": "America/Atikokan",
  "ca-5": "America/Toronto",
  ky: "America/Cayman",
  co: "America/Bogota",
  "ec-5": "America/Guayaquil",
  jm: "America/Jamaica",
  "mx-5": "America/Cancun",
  pa: "America/Panama",
  pe: "America/Lima",
  "um-5": "Etc/GMT+5",
  "us-5": "America/New_York",
  bs: "America/Nassau",
  cu: "America/Havana",
  ht: "America/Port-au-Prince",
  tc: "America/Grand_Turk",

  ai: "America/Anguilla",
  ag: "America/Antigua",
  aw: "America/Aruba",
  bb: "America/Barbados",
  bo: "America/La_Paz",
  "br-4": "America/Manaus",
  vg: "America/Tortola",
  "ca-4n": "America/Blanc-Sablon",
  "ca-4": "America/Halifax",
  bq: "America/Kralendijk",
  cw: "America/Curacao",
  dm: "America/Dominica",
  do: "America/Santo_Domingo",
  gd: "America/Grenada",
  gp: "America/Guadeloupe",
  gy: "America/Guyana",
  mq: "America/Martinique",
  ms: "America/Montserrat",
  pr: "America/Puerto_Rico",
  bl: "America/St_Barthelemy",
  kn: "America/St_Kitts",
  lc: "America/St_Lucia",
  mf: "America/Marigot",
  vc: "America/St_Vincent",
  sx: "America/Lower_Princes",
  tt: "America/Port_of_Spain",
  vi: "America/St_Thomas",
  ve: "America/Caracas",
  "cl-4": "America/Santiago",
  "gl-4": "America/Thule",
  bm: "Atlantic/Bermuda",

  "ca-330": "America/St_Johns",

  ar: "America/Buenos_Aires",
  "br-3": "America/Sao_Paulo",
  "cl-3": "America/Santiago",
  fk: "Atlantic/Stanley",
  gf: "America/Cayenne",
  py: "America/Asuncion",
  sr: "America/Paramaribo",
  uy: "America/Montevideo",

  "br-2": "America/Noronha",
  gs: "Atlantic/South_Georgia",
  "gl-2": "America/Nuuk",

  cv: "Atlantic/Cape_Verde",
  "pt-1": "Atlantic/Azores",

  fo: "Atlantic/Faeroe",
  gg: "Europe/Guernsey",
  ie: "Europe/Dublin",
  im: "Europe/Isle_of_Man",
  je: "Europe/Jersey",
  pt0: "Europe/Lisbon",
  ic: "Atlantic/Canary",
  gb: "Europe/London",
  gl0: "America/Danmarkshavn",
  sn: "Africa/Dakar",
  gm: "Africa/Banjul",
  gw: "Africa/Bissau",
  sl: "Africa/Freetown",
  gn: "Africa/Conakry",
  lr: "Africa/Monrovia",
  ml: "Africa/Bamako",
  bf: "Africa/Ouagadougou",
  ci: "Africa/Abidjan",
  gh: "Africa/Accra",
  sh: "Atlantic/St_Helena",
  mr: "Africa/Nouakchott",
  tg: "Africa/Lome",
  st: "Africa/Sao_Tome",

  al: "Europe/Tirane",
  ad: "Europe/Andorra",
  at: "Europe/Vienna",
  be: "Europe/Brussels",
  ba: "Europe/Sarajevo",
  bv: "Europe/Oslo",
  hr: "Europe/Zagreb",
  cz: "Europe/Prague",
  dk: "Europe/Copenhagen",
  fr: "Europe/Paris",
  de: "Europe/Berlin",
  gi: "Europe/Gibraltar",
  hu: "Europe/Budapest",
  it: "Europe/Rome",
  kosovo: "Europe/Belgrade",
  li: "Europe/Vaduz",
  lu: "Europe/Luxembourg",
  mt: "Europe/Malta",
  mc: "Europe/Monaco",
  me: "Europe/Podgorica",
  nl: "Europe/Amsterdam",
  mk: "Europe/Skopje",
  no: "Europe/Oslo",
  pl: "Europe/Warsaw",
  sm: "Europe/San_Marino",
  rs: "Europe/Belgrade",
  sk: "Europe/Bratislava",
  si: "Europe/Ljubljana",
  es: "Europe/Madrid",
  se: "Europe/Stockholm",
  ch: "Europe/Zurich",
  va: "Europe/Vatican",
  tn: "Africa/Tunis",
  dz: "Africa/Algiers",
  ma: "Africa/Casablanca",
  bj: "Africa/Porto-Novo",
  ne: "Africa/Niamey",
  ng: "Africa/Lagos",
  td: "Africa/Ndjamena",
  cm: "Africa/Douala",
  cg: "Africa/Brazzaville",
  gq: "Africa/Malabo",
  ga: "Africa/Libreville",
  na: "Africa/Windhoek",
  cd1: "Africa/Kinshasa",

  ax: "Europe/Mariehamn",
  bg: "Europe/Sofia",
  cy: "Asia/Nicosia",
  eg: "Africa/Cairo",
  ee: "Europe/Tallinn",
  fi: "Europe/Helsinki",
  gr: "Europe/Athens",
  il: "Asia/Jerusalem",
  lv: "Europe/Riga",
  lb: "Asia/Beirut",
  lt: "Europe/Vilnius",
  md: "Europe/Chisinau",
  northerncyprus: "Asia/Famagusta",
  ps: "Asia/Gaza",
  ro: "Europe/Bucharest",
  transnistria: "Europe/Chisinau",
  ua2: "Europe/Kiev",
  za2: "Africa/Johannesburg",
  ss: "Africa/Juba",
  sd: "Africa/Khartoum",
  cd2: "Africa/Lubumbashi",
  rw: "Africa/Kigali",
  bi: "Africa/Bujumbura",
  ao: "Africa/Luanda",
  ls: "Africa/Maseru",
  sz: "Africa/Mbabane",
  bw: "Africa/Gaborone",
  zm: "Africa/Lusaka",
  zw: "Africa/Harare",
  mw: "Africa/Blantyre",
  mz: "Africa/Maputo",
  ly: "Africa/Tripoli",

  abkhazia: "Europe/Moscow",
  bh: "Asia/Bahrain",
  by: "Europe/Minsk",
  km: "Indian/Comoro",
  dj: "Africa/Djibouti",
  er: "Africa/Asmera",
  et: "Africa/Addis_Ababa",
  tf3: "Indian/Kerguelen",
  iq: "Asia/Baghdad",
  jo: "Asia/Amman",
  ke: "Africa/Nairobi",
  kw: "Asia/Kuwait",
  mg: "Indian/Antananarivo",
  yt: "Indian/Mayotte",
  qa: "Asia/Qatar",
  ru3: "Europe/Moscow",
  sa: "Asia/Riyadh",
  so: "Africa/Mogadishu",
  somaliland: "Africa/Mogadishu",
  za3: "Africa/Johannesburg",
  southossetia: "Europe/Moscow",
  sy: "Asia/Damascus",
  tz: "Africa/Dar_es_Salaam",
  tr: "Europe/Istanbul",
  ug: "Africa/Kampala",
  ua3: "Europe/Simferopol",

  ir: "Asia/Tehran",

  am: "Asia/Yerevan",
  az: "Asia/Baku",
  tf4: "Indian/Kerguelen",
  ge: "Asia/Tbilisi",
  om: "Asia/Muscat",
  ru4: "Europe/Samara",
  mu: "Indian/Mauritius",
  re: "Indian/Reunion",
  sc: "Indian/Mahe",
  ae: "Asia/Dubai",
  ashmorecartier: "Etc/GMT-4",

  af: "Asia/Kabul",

  kz: "Asia/Almaty",
  mv: "Indian/Maldives",
  pk: "Asia/Karachi",
  ru5: "Asia/Yekaterinburg",
  tj: "Asia/Dushanbe",
  tm: "Asia/Ashgabat",
  uz: "Asia/Tashkent",

  in: "Asia/Calcutta",
  lk: "Asia/Colombo",

  np: "Asia/Katmandu",

  bd: "Asia/Dhaka",
  bt: "Asia/Thimphu",
  io: "Indian/Chagos",
  kg: "Asia/Bishkek",
  ru6: "Asia/Omsk",

  cc: "Indian/Cocos",
  mm: "Asia/Rangoon",

  kh: "Asia/Phnom_Penh",
  cx: "Indian/Christmas",
  id7: "Asia/Jakarta",
  la: "Asia/Vientiane",
  mn7: "Asia/Hovd",
  ru7: "Asia/Krasnoyarsk",
  th: "Asia/Bangkok",
  vn: "Asia/Saigon",

  au8: "Australia/Perth",
  bn: "Asia/Brunei",
  cn: "Asia/Shanghai",
  hk: "Asia/Hong_Kong",
  id8: "Asia/Makassar",
  mo: "Asia/Macau",
  my: "Asia/Kuala_Lumpur",
  mn8: "Asia/Ulaanbaatar",
  ph: "Asia/Manila",
  ru8: "Asia/Irkutsk",
  sg: "Asia/Singapore",
  tw: "Asia/Taipei",

  au845: "Australia/Eucla",

  tl: "Asia/Dili",
  id9: "Asia/Jayapura",
  jp: "Asia/Tokyo",
  kp: "Asia/Pyongyang",
  pw: "Pacific/Palau",
  ru9: "Asia/Yakutsk",
  kr: "Asia/Seoul",

  au930n: "Australia/Darwin",
  au930: "Australia/Adelaide",

  au10n: "Australia/Brisbane",
  au10: "Australia/Sydney",
  coralsea10: "Australia/Brisbane",
  gu: "Pacific/Guam",
  fm10: "Pacific/Truk",
  mp: "Pacific/Saipan",
  pg10: "Pacific/Port_Moresby",
  ru10: "Asia/Vladivostok",

  au1030: "Australia/Lord_Howe",

  coralsea11: "Pacific/Noumea",
  fm11: "Pacific/Kosrae",
  nc: "Pacific/Noumea",
  pg11: "Pacific/Bougainville",
  ru11: "Asia/Magadan",
  sb: "Pacific/Guadalcanal",
  vu: "Pacific/Efate",
  nf: "Pacific/Norfolk",

  fj: "Pacific/Fiji",
  ki12: "Pacific/Tarawa",
  mh: "Pacific/Majuro",
  nr: "Pacific/Nauru",
  ru12: "Asia/Kamchatka",
  tv: "Pacific/Funafuti",
  wf: "Pacific/Wallis",
  nz12: "Pacific/Auckland",

  nz1245: "Pacific/Chatham",

  ki13: "Pacific/Enderbury",
  ws: "Pacific/Apia",
  tk: "Pacific/Fakaofo",
  to: "Pacific/Tongatapu",

  ki14: "Pacific/Kiritimati",
};
